## Documentação de Contexto
 
O município de Cristália-MG enfrenta diversos desafios sociais, especialmente relacionados à vulnerabilidade de crianças de famílias em situação de carência financeira. Nesse cenário, a Igreja Remanescente Família de Deus desenvolve um projeto social de grande valor comunitário, atuando diretamente no suporte a essas crianças.
 
O projeto funciona com dois encontros semanais, realizados às terças-feiras e aos sábados. As crianças são transportadas até a igreja em veículos conduzidos por motoristas voluntários, uma vez que a maioria dos pais não possui condições financeiras para levá-las. Durante os encontros, as crianças recebem ensinos bíblicos fundamentados na Palavra de Deus, participam de palestras educativas sobre temas diversos e relevantes para sua formação, recebem doações de roupas coletadas e organizadas pela comunidade da igreja e também cestas básicas, em que os membros contribuem periodicamente com alimentos. Além disso, a Assistência Social do município atua em parceria, encaminhando periodicamente novas crianças em situação de vulnerabilidade para serem assistidas.
 
Apesar da relevância do projeto, sua gestão ainda ocorre de forma informal, o que gera diversos problemas, como: desorganização no agendamento e controle dos motoristas voluntários, ocorrendo por vezes de não haver motorista disponível para buscar crianças que moram mais distantes; ausência de critérios estruturados para identificar e priorizar as famílias em maior necessidade, considerando que a capacidade de atendimento não é grande; falta de centralização das informações sobre cadastros, doações e voluntários, dificultando saber com clareza quanto foi doado, quando, para quem e quem mais necessita; além da dificuldade em acompanhar resultados e medir o impacto real das ações, como o número de famílias alcançadas e a evolução do apoio oferecido.
 
Diante desse cenário, surge a necessidade de uma solução tecnológica capaz de trazer mais eficiência, transparência e organização às atividades realizadas, ampliando o alcance e a efetividade do projeto. Essa iniciativa se alinha aos Objetivos de Desenvolvimento Sustentável (ODS) 1 – Erradicação da Pobreza, 2 – Fome Zero e Agricultura Sustentável e 10 – Redução das Desigualdades.
 
## Especificação do Projeto
 
O presente projeto extensionista tem como objetivo desenvolver uma solução em Excel, com interface personalizada e funcionalidades de Business Intelligence (BI), para apoiar a gestão do projeto social da Igreja Remanescente Família de Deus em Cristália-MG. A ferramenta será auto-suficiente, funcionando como sistema de cadastro, organização e análise, e será disponibilizada por meio de um link de acesso para os gestores e voluntários da iniciativa.
 
O objetivo geral consiste em criar um sistema em Excel, estruturado com menus interativos, tabelas de cadastro e dashboards visuais, capaz de organizar as informações do projeto social, otimizar processos e fornecer relatórios de impacto. Entre os objetivos específicos, destacam-se: criar cadastros organizados de voluntários (motoristas e professores) e famílias atendidas; estruturar uma lista de espera para crianças encaminhadas pelo CRAS, voluntários ou pela própria igreja; implementar uma escala semanal de voluntários; desenvolver um dashboard geral com indicadores de quantidade de crianças atendidas, famílias alcançadas e voluntários ativos; e fornecer acesso online via link, permitindo que diferentes membros possam utilizar a ferramenta sem necessidade de softwares complexos.
 
A metodologia será baseada em três componentes principais: um menu lateral interativo, criado com botões que direcionam para cada funcionalidade (Cadastro de Voluntários, Cadastro Familiar, Escala Semanal de Voluntários e Dashboard Geral); tabelas estruturadas para organizar as informações de motoristas, professores, famílias e listas de espera; e um dashboard geral, com indicadores e gráficos dinâmicos que permitem acompanhar os resultados de forma clara e rápida.
 
O fluxo de operação será simples: os voluntários, o CRAS ou membros da igreja preencherão os cadastros; as informações alimentarão automaticamente as planilhas auxiliares e listas de espera; os dashboards serão atualizados em tempo real, permitindo a análise dos dados; e os gestores poderão acessar a ferramenta de forma prática por meio de link compartilhado.
 
Espera-se como resultado a centralização das informações sobre famílias, crianças, voluntários e doações; a redução da desorganização nas escalas de motoristas e professores; a definição de critérios claros de priorização de famílias em lista de espera; maior transparência na prestação de contas das ações sociais; e a visualização clara do impacto do projeto, incluindo a quantidade de famílias e crianças alcançadas.
